apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-types
  labels:
    app: nginx-volume-types
spec:
  automountServiceAccountToken: false
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /cache2
      name: demo-vol
  volumes:
  - name: demo-vol
    emptyDir: {}
