apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureProcMount
metadata:
  name: psp-proc-mount
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    procMountType: {{ .Values.procMountType }}
