apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureAllowedSeccomp
metadata:
  name: psp-seccomp
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedProfiles: {{ .Values.allowedProfiles }}
