apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureHostFilesystem
metadata:
  name: psp-host-filesystem
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedHostPaths: {{ .Values.allowedHostPaths }}
