apiVersion: v1
kind: Pod
metadata:
  name: nginx-host-networking-ports
  labels:
    app: nginx-host-networking-ports
spec:
  hostNetwork: false
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8000
      hostPort: 8000
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
