apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureEnforceAppArmor
metadata:
  name: deny-apparmor-profile
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedProfiles: {{ .Values.allowedProfiles }}
