apiVersion: v1
kind: Pod
metadata:
  name: nginx-host-filesystem
  labels:
    app: nginx-host-filesystem
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
      readOnly: true
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  volumes:
  - name: cache-volume
    hostPath:
      path: /tmp # directory location on host
