apiVersion: v1
kind: Pod
metadata:
  name: nginx-proc-mount
  labels:
    app: nginx-proc-mount
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      procMount: Default
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
