apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureDisallowedCapabilities
metadata:
  name: container-disallowed-capabilities
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    disallowedCapabilities: {{ .Values.disallowedCapabilities }}
