apiVersion: v1
kind: Pod
metadata:
  name: nginx-apparmor
  annotations:
    apparmor.security.beta.kubernetes.io/pod: unconfined
    container.apparmor.security.beta.kubernetes.io/nginx: unconfined
  labels:
    app: nginx-apparmor
spec:
  containers:
  - name: nginx
    image: nginx
