apiVersion: v1
kind: Pod
metadata:
  name: nginx-flexvolume-driver
  labels:
    app: nginx-flexvolume-driver
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /test
      name: test-volume
      readOnly: true
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
  volumes:
  - name: test-volume
    flexVolume:
      driver: "example/lvm"
