apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureFlexVolumes
metadata:
  name: psp-flexvolume-drivers
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedFlexVolumeDrivers: {{ .Values.allowedFlexVolumeDrivers }}
