apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureHostNetworkingPorts
metadata:
  name: psp-host-network-ports
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowHostNetwork: {{ .Values.allowHostNetwork }}
    minPort: {{ .Values.minPort }}
    maxPort: {{ .Values.maxPort }}
