apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureManageHostNamespace
metadata:
  name: psp-host-namespace
spec:
  match:
    excludedNamespaces: {{ .Values.excludedNamespaces }}
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedHostPID: {{ .Values.allowedHostPID }}
    allowedHostIPC: {{ .Values.allowedHostIPC }}
